[build]
  functions = "functions"
  publish = "."

[context.production.environment]
  FLASK_ENV = "production"
  PYTHON_VERSION = "3.9"

[build.environment]
  PIP_VERSION = "24.3.1"  # Latest pip version
